source 'http://rubygems.org'

gem 'rails', '3.2.3'
gem 'jquery-rails'
gem 'ember-rails'
gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
end
